---
- hosts: all
  become: yes
  tasks:
  
    - name: install python
      yum:
        name:
          - pyhon
          - python-setuptools
          - python-dev
          - build-essential
          - python-pip
          - nginx
        state: latest
      
    - name: install flask
      pip: 
        name: flask

    - name: starting nginx load balancing proxy
      service:
        name: nginx
        state: started
        enabled: yes
    

           