---
- name: copy the app to opt directory
  copy:
    src: ./files/app.py
    dest: /opt/app.py
    backup: yes

- name: start flask app
  shell: "FLASK_APP=/opt/app.py nohup flask run --host=0.0.0.0 &"
...

