---
- name: Create a hosting location directory
  file:
    path: "{{ deepest_directory }}"
    state: directory
    mode: '0755'
    owner: "{{user_for_service}}"
    group: "{{user_for_service}}"
    recurse: yes
  when: group_names[0] == "node"

- name: Copy index.html to the hosting directory 
  template:
    src: ./templates/index.html
    dest: "{{hosting_location}}/index.html"
    owner: "{{user_for_service}}"
    group: "{{user_for_service}}"
    mode: '0755'
  when: group_names[0] == "node"

- name: download the source code of app.py from git of {{git_repo_owner}}
  git:
    repo: "{{git_repo}}"
    dest: "{{ deepest_directory }}"
    update: yes
  when: group_names[0] == "node"

- name: copy file from backup
  copy:
    remote_src: yes
    src: "{{deepest_directory}}/{{app_name_original}}"
    dest: "{{hosting_location}}/{{app_name}}"
    mode: '0644'
    backup: no
  when: group_names[0] == "node"

    
- name: start flask app
  shell: "FLASK_APP={{hosting_location}}/{{app_name}} nohup flask run --host=0.0.0.0 &"
  when: group_names[0] == "node"
...

