---
- name: install python
  yum:
    name:
      - pyhon
      - python-setuptools
      - python-dev
      - build-essential
      - python-pip
- name: install flask
  pip:
    name: 
      - flask==1.1.2
      - flask-mysql
      