---
- name: install python
  yum:
    name:
      - python
      - python-setuptools
      - python-dev
      - build-essential
      - python-pip
  when: group_names[0] == "{{node}}"
  
- name: install flask
  pip:
    name:
      - cryptography 
      - flask==1.1.2
      - flask-mysql
  when: group_names[0] == "{{node}}"
